# Indexing

In [1]:
# melbourne data
import pandas as pd

melbourne_data = pd.read_csv("../inputs/melb_data.csv")

Selecting specific values of pandas DataFrame or Series to work.

In [2]:
melbourne_data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [3]:
melbourne_data.Suburb

0           Abbotsford
1           Abbotsford
2           Abbotsford
3           Abbotsford
4           Abbotsford
             ...
13575    Wheelers Hill
13576     Williamstown
13577     Williamstown
13578     Williamstown
13579       Yarraville
Name: Suburb, Length: 13580, dtype: str

In [4]:
melbourne_data["Rooms"]

0        2
1        2
2        3
3        3
4        4
        ..
13575    4
13576    3
13577    3
13578    4
13579    4
Name: Rooms, Length: 13580, dtype: int64

In [5]:
melbourne_data["Lattitude"][0]

np.float64(-37.7996)

# Indexing in pandas

## Index based selection

In [6]:
melbourne_data.iloc[0]

Suburb                      Abbotsford
Address                   85 Turner St
Rooms                                2
Type                                 h
Price                        1480000.0
Method                               S
SellerG                         Biggin
Date                         3/12/2016
Distance                           2.5
Postcode                        3067.0
Bedroom2                           2.0
Bathroom                           1.0
Car                                1.0
Landsize                         202.0
BuildingArea                       NaN
YearBuilt                          NaN
CouncilArea                      Yarra
Lattitude                     -37.7996
Longtitude                    144.9984
Regionname       Northern Metropolitan
Propertycount                   4019.0
Name: 0, dtype: object

Both `iloc` and `loc` are row-first, column-second

In [7]:
melbourne_data.iloc[:, 0]

0           Abbotsford
1           Abbotsford
2           Abbotsford
3           Abbotsford
4           Abbotsford
             ...
13575    Wheelers Hill
13576     Williamstown
13577     Williamstown
13578     Williamstown
13579       Yarraville
Name: Suburb, Length: 13580, dtype: str

`:` comes from native python, means "everything"

In [8]:
melbourne_data.iloc[:3, 0]

0    Abbotsford
1    Abbotsford
2    Abbotsford
Name: Suburb, dtype: str

In [9]:
melbourne_data.iloc[1:3, 0]

1    Abbotsford
2    Abbotsford
Name: Suburb, dtype: str

Its also possible to pass a list.

In [10]:
melbourne_data.iloc[[0, 1, 3], 0]

0    Abbotsford
1    Abbotsford
3    Abbotsford
Name: Suburb, dtype: str

In [11]:
melbourne_data.iloc[-5, :]

Suburb                        Wheelers Hill
Address                        12 Strada Cr
Rooms                                     4
Type                                      h
Price                             1245000.0
Method                                    S
SellerG                               Barry
Date                             26/08/2017
Distance                               16.7
Postcode                             3150.0
Bedroom2                                4.0
Bathroom                                2.0
Car                                     2.0
Landsize                              652.0
BuildingArea                            NaN
YearBuilt                            1981.0
CouncilArea                             NaN
Lattitude                         -37.90562
Longtitude                        145.16761
Regionname       South-Eastern Metropolitan
Propertycount                        7392.0
Name: 13575, dtype: object

### Label-Based Selection

The second paradigm for attribute selection is the one followed by the `loc` operator: __label-based selection__. In this paradigm, it's the data index value, not its position, which matters.

In [12]:
melbourne_data.loc[0, "Address"]

'85 Turner St'

In [13]:
melbourne_data.loc[1:10, ["Rooms", "Type", "Price", "Method", "SellerG"]] # row inclusive

    Rooms Type      Price Method SellerG
1       2    h  1035000.0      S  Biggin
2       3    h  1465000.0     SP  Biggin
3       3    h   850000.0     PI  Biggin
4       4    h  1600000.0     VB  Nelson
5       2    h   941000.0      S  Jellis
6       3    h  1876000.0      S  Nelson
7       2    h  1636000.0      S  Nelson
8       1    u   300000.0      S  Biggin
9       2    h  1097000.0      S  Biggin
10      2    u   700000.0     VB  Jellis

In [14]:
melbourne_data.loc["Room":"Type"]

Empty DataFrame
Columns: [Suburb, Address, Rooms, Type, Price, Method, SellerG, Date, Distance, Postcode, Bedroom2, Bathroom, Car, Landsize, BuildingArea, YearBuilt, CouncilArea, Lattitude, Longtitude, Regionname, Propertycount]
Index: []

[0 rows x 21 columns]

### Manipulating the Index

Label-based selection derives its power from the labels in the index. Critically, the index we use is not immutable.
The `set_index()` method can be used to set a specific column as index.

In [15]:
melbourne_data.set_index("Address")

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
Address,,,,,,,,,,,,,,,,,,,,
85 Turner St,Abbotsford,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
25 Bloomburg St,Abbotsford,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
5 Charles St,Abbotsford,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
40 Federation La,Abbotsford,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
55a Park St,Abbotsford,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12 Strada Cr,Wheelers Hill,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
77 Merrett Dr,Williamstown,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
83 Power St,Williamstown,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
96 Verdon St,Williamstown,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
6 Agnes St,Yarraville,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

### Conditional selection

In [16]:
melbourne_data.Type == "h"

0        True
1        True
2        True
3        True
4        True
         ...
13575    True
13576    True
13577    True
13578    True
13579    True
Name: Type, Length: 13580, dtype: bool

In [17]:
melbourne_data.loc[melbourne_data.Type == "h"]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [18]:
melbourne_data.loc[(melbourne_data.Method == "S") & (melbourne_data.SellerG == "Biggin")].tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13079,West Footscray,28 Tucker St,2,h,855000.0,S,Biggin,19/08/2017,6.4,3012.0,...,1.0,1.0,332.0,NaN,NaN,NaN,-37.79136,144.87619,Western Metropolitan,5058.0
13480,Maidstone,3 Wallace St,3,h,735000.0,S,Biggin,26/08/2017,6.4,3012.0,...,1.0,1.0,167.0,110.0,2010.0,NaN,-37.78817,144.87873,Western Metropolitan,3873.0
13505,Mulgrave,2229 Dandenong Rd,3,h,940000.0,S,Biggin,26/08/2017,18.8,3170.0,...,2.0,3.0,709.0,140.0,1958.0,NaN,-37.92811,145.14971,South-Eastern Metropolitan,7113.0
13523,Prahran,69 Greville St,4,h,2668000.0,S,Biggin,26/08/2017,4.6,3181.0,...,2.0,2.0,383.0,NaN,NaN,NaN,-37.84879,144.98882,Southern Metropolitan,7717.0
13531,Richmond,170 Coppin St,4,h,1800000.0,S,Biggin,26/08/2017,2.4,3121.0,...,1.0,4.0,418.0,NaN,NaN,NaN,-37.82368,145.00271,Northern Metropolitan,14949.0

In [19]:
melbourne_data.loc[melbourne_data.Suburb.isin(["West Footscray", "Prahran"])]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4804,Prahran,7/36 Grandview Gr,2,u,650000.0,VB,Hodges,3/09/2016,4.5,3181.0,...,1.0,1.0,0.0,NaN,NaN,Stonnington,-37.85000,145.00850,Southern Metropolitan,7717.0
4805,Prahran,13/37 Greville St,1,u,342000.0,S,hockingstuart,3/09/2016,4.5,3181.0,...,1.0,1.0,0.0,34.0,1960.0,Stonnington,-37.84860,144.98720,Southern Metropolitan,7717.0
4806,Prahran,20a Percy St,2,h,950000.0,PI,hockingstuart,3/09/2016,4.5,3181.0,...,1.0,1.0,88.0,121.0,2000.0,Stonnington,-37.85030,144.99130,Southern Metropolitan,7717.0
4807,Prahran,3/122 Williams Rd,2,u,781000.0,S,Wilson,3/09/2016,4.5,3181.0,...,1.0,1.0,0.0,73.0,1930.0,Stonnington,-37.85110,145.00290,Southern Metropolitan,7717.0
4808,Prahran,907/15 Clifton St,1,u,549800.0,S,hockingstuart,3/12/2016,4.5,3181.0,...,1.0,1.0,0.0,51.0,2012.0,Stonnington,-37.85190,144.99480,Southern Metropolitan,7717.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13267,Prahran,7 MacKay St,3,t,1463000.0,S,Jellis,23/09/2017,4.6,3181.0,...,2.0,2.0,15.0,147.0,1998.0,NaN,-37.84969,145.00057,Southern Metropolitan,7717.0
13324,West Footscray,702 Barkly St,3,h,840000.0,PI,Hodges,23/09/2017,6.4,3012.0,...,1.0,3.0,336.0,95.0,1950.0,NaN,-37.79613,144.86742,Western Metropolitan,5058.0
13325,West Footscray,171 Essex St,3,h,879000.0,SP,Jas,23/09/2017,6.4,3012.0,...,1.0,2.0,377.0,NaN,NaN,NaN,-37.79285,144.86969,Western Metropolitan,5058.0
13523,Prahran,69 Greville St,4,h,2668000.0,S,Biggin,26/08/2017,4.6,3181.0,...,2.0,2.0,383.0,NaN,NaN,NaN,-37.84879,144.98882,Southern Metropolitan,7717.0
13524,Prahran,17 Packington Pl,2,h,1365000.0,S,Jellis,26/08/2017,4.6,3181.0,...,1.0,NaN,206.0,100.0,1900.0,NaN,-37.85569,145.00522,Southern Metropolitan,7717.0

In [20]:
melbourne_data.loc[melbourne_data.YearBuilt.notnull()]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

### Assigning data

In [21]:
melbourne_data["Rooms"] = melbourne_data["Rooms"] + 1
melbourne_data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,3,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,3,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,4,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,4,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,5,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,5,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,4,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,4,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,5,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,5,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0