# Grouping and Sorting

In [2]:
import pandas as pd

reviews = pd.read_csv("../inputs/winemag-data-130k-v2.csv", index_col=0)
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
reviews.groupby("points").count()

,country,description,designation,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
points,,,,,,,,,,,,
80,397,397,250,395,397,328,136,275,271,397,397,397
81,692,692,406,680,692,584,293,433,423,692,692,692
82,1835,1836,1087,1772,1835,1556,907,1054,1012,1836,1836,1836
83,3024,3025,1844,2886,3024,2503,1142,2112,2021,3025,3025,3025
84,6478,6480,3943,6099,6478,5320,2375,4395,4196,6480,6480,6480
85,9529,9530,5980,8902,9529,7722,3308,7133,6729,9530,9530,9530
86,12595,12600,8246,11745,12595,10361,4467,9580,9006,12600,12600,12600
87,16927,16933,11286,15767,16927,14293,6102,12871,12065,16933,16933,16933
88,17198,17207,11831,16014,17198,14503,6538,14356,13626,17207,17206,17207
89,12208,12226,8920,11324,12208,9998,4095,10660,10056,12226,12226,12226
90,15403,15410,11412,14361,15403,12747,6349,12946,12291,15410,15410,15410
91,11353,11359,8858,10564,11353,9583,5006,9765,9442,11359,11359,11359
92,9606,9613,7887,8871,9606,8185,4279,7833,7612,9613,9613,9613
93,6489,6489,5457,5935,6489,5611,2854,5408,5239,6489,6489,6489
94,3758,3758,3166,3449,3758,3317,1696,3018,2924,3758,3758,3758
95,1535,1535,1249,1406,1535,1332,623,1221,1190,1535,1535,1535
96,523,523,419,482,523,458,216,405,396,523,523,523
97,229,229,170,207,229,203,77,166,164,229,229,229
98,77,77,53,69,77,72,32,61,60,77,77,77
99,33,33,29,28,33,31,12,21,21,33,33,33
100,19,19,13,19,19,17,4,14,14,19,19,19

In [4]:
reviews.groupby("points").max()

,country,description,designation,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
points,,,,,,,,,,,,
80,Uruguay,"Yellowish in color, a true indicator that this...",“Champ” Jim the Gent,69.0,Washington,York Mountain,Willamette Valley,Virginie Boone,@wineschach,oops 2011 Carmenère (Central Valley),Zinfandel,oops
81,Uruguay,"Yellow straw, oxidized, with dull and flat fla...",“Champ” Lightnin' Lane,130.0,Washington,Yountville,Willamette Valley,Virginie Boone,@wineschach,flipflop NV Left Coast Pinot Noir (Chile),Zinfandel,flipflop
82,Uruguay,"Zingy and sort of floral on the nose, but fair...",ops,150.0,Western Australia,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Ñandú 2010 Malbec (Mendoza),Zweigelt,Ñandú
83,Uruguay,"“Light” is misleading, because this really isn...",À Côté,225.0,Štajerska,Zonda Valley,Willamette Valley,Virginie Boone,@worldwineguys,Ébano 2014 6 (Ribera del Duero),Zweigelt,Ébano
84,Uruguay,“The Affair” refers to the relationship betwee...,redFOUR,225.0,Österreichischer Sekt,Zonda Valley,Willamette Valley,Virginie Boone,@worldwineguys,Ébano 2007 6 (Ribera del Duero),Zweigelt,Ébano
85,Uruguay,‘Na Vota is a fresh and easygoing wine that is...,Ópera Prima,320.0,Štajerska,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Öko 2013 Made With Organically Grown Grapes Ma...,Zweigelt,Öko
86,Uruguay,"“Sangue Blu,” which translates to “blue blood,...",Über Cuvée,170.0,Župa,Zonda Valley,Willamette Valley,Virginie Boone,@worldwineguys,Çamlibağ 2012 Kuntra (Turkey),Çalkarası,Çamlibağ
87,Uruguay,"“Terre Nobili,” which is Italian for “noble la...",“P”,800.0,Štajerska,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Çamlibağ 2012 Karalahna (Turkey),Çalkarası,Çamlibağ
88,Uruguay,“Three winds” is a new product from a top Pros...,Župska,3300.0,Župa,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Štoka 2009 Izbrani Teran (Kras),Žilavka,Štoka
89,Uruguay,"“Open and drink” the instructions should read,...",‘Rough Justice' Red,500.0,Župa,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,àMaurice NV Pour Me Red (Columbia Valley (WA)),Zweigelt,àMaurice
90,Uruguay,“Swan Song” indicates that this is the last vi...,étoile Brut,510.0,Štajerska,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Štoka 2011 Izbrani Teran (Kras),Zweigelt,Štoka
91,Uruguay,“Gas station” isn't necessarily the most attra...,Ürziger Würzgarten Spätlese,2013.0,Österreichischer Sekt,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,àMaurice 2013 Sparrow Estate Viognier Viognier...,Zweigelt,àMaurice
92,Uruguay,“Wow” is the first word that comes to mind whe...,‘S',750.0,Österreichischer Sekt,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,àMaurice 2011 Boushey Vineyard Syrah (Yakima V...,Zweigelt,àMaurice
93,US,"plush wine, it's made from 80% Cabernet Sauvig...",Ürziger Würzgarten Spätlese,770.0,Österreichischer Sekt,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,àMaurice 2011 Gamache Vineyard Malbec (Columbi...,Zweigelt,àMaurice
94,US,Zind-Humbrecht owns some great Grand Cru viney...,Ürziger Würzgarten Auslese,1125.0,Western Australia,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,àMaurice 2008 Red (Columbia Valley (WA)),Zweigelt,àMaurice
95,US,"Young and tart in cool-climate acidity, this P...",Ürziger Würzgarten Spätlese,973.0,Österreichischer Sekt,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Ökonomierat Rebholz 2011 Trocken Spätburgunder...,Zinfandel,Ökonomierat Rebholz
96,US,"Youthfully flippant, this block of the Wayfare...",Ürziger Würzgarten Auslese * * * Goldkap,2500.0,Washington,Yountville,Willamette Valley,Virginie Boone,@worldwineguys,Zaca Mesa 2009 Black Bear Block Estate Grown a...,Zinfandel,Zaca Mesa
97,US,You may have to scour the country to secure so...,by Montes Aurelio's Selection,2000.0,Washington,Willamette Valley,Washington Other,Virginie Boone,@worldwineguys,Yao Ming 2009 Family Reserve Cabernet Sauvigno...,Zinfandel,Yao Ming
98,US,"With this wine, Dolce cements its status as Ca...",Zwischen den Seen Nummer 9 Trockenbeerenauslese,1900.0,Washington,Walla Walla Valley (WA),Sonoma,Virginie Boone,@wineschach,Yao Ming 2010 Family Reserve Cabernet Sauvigno...,Welschriesling,Yao Ming
99,US,This wine is dark brown in hue with a greenish...,Vargellas Vinhas Velhas Vintage,850.0,Washington,Walla Walla Valley (OR),Sonoma,Virginie Boone,@vossroger,Williams Selyem 2010 Hirsch Vineyard Pinot Noi...,Syrah,Williams Selyem
100,US,This wine dazzles with perfection. Sourced fro...,Royal City,1500.0,Washington,Walla Walla Valley (WA),Sonoma,Roger Voss,@vossroger,Verité 2007 La Muse Red (Sonoma County),Syrah,Verité

In [5]:
reviews.head(30).groupby("points").sum()

,country,description,designation,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
points,,,,,,,,,,,,
86,US,Clarksburg is becoming a haven for Chenin Blan...,,16.0,California,Clarksburg,Central Valley,Virginie Boone,@vboone,Clarksburg Wine Company 2010 Chenin Blanc (Cla...,Chenin Blanc,Clarksburg Wine Company
87,ItalyPortugalUSUSUSSpainItalyFranceGermanyFran...,"Aromas include tropical fruit, broom, brimston...",Vulkà BiancoAvidagosReserve Late HarvestVintne...,651.0,Sicily & SardiniaDouroOregonMichiganOregonNort...,EtnaWillamette ValleyLake Michigan ShoreWillam...,Willamette ValleyWillamette ValleyNapaSonomaCe...,Kerin O’KeefeRoger VossPaul GreguttAlexander P...,@kerinokeefe@vossroger@paulgwine @paulgwine @w...,Nicosia 2013 Vulkà Bianco (Etna)Quinta dos Av...,White BlendPortuguese RedPinot GrisRieslingPin...,NicosiaQuinta dos AvidagosRainstormSt. JulianS...

## Aggregations

In [6]:
reviews.groupby("points").agg({"points": ["mean", "max", "count", "sum"]})

       points
         mean  max  count      sum
points
80       80.0   80    397    31760
81       81.0   81    692    56052
82       82.0   82   1836   150552
83       83.0   83   3025   251075
84       84.0   84   6480   544320
85       85.0   85   9530   810050
86       86.0   86  12600  1083600
87       87.0   87  16933  1473171
88       88.0   88  17207  1514216
89       89.0   89  12226  1088114
90       90.0   90  15410  1386900
91       91.0   91  11359  1033669
92       92.0   92   9613   884396
93       93.0   93   6489   603477
94       94.0   94   3758   353252
95       95.0   95   1535   145825
96       96.0   96    523    50208
97       97.0   97    229    22213
98       98.0   98     77     7546
99       99.0   99     33     3267
100     100.0  100     19     1900

In [7]:
reviews.groupby("points").describe()

          price
          count        mean         std   min    25%    50%    75%     max
points
80        395.0   16.372152    8.476347   5.0   11.0   14.0   19.0    69.0
81        680.0   17.182353   11.913989   5.0   10.0   14.0   20.0   130.0
82       1772.0   18.870767   11.029231   4.0   12.0   15.0   24.0   150.0
83       2886.0   18.237353   11.568984   4.0   11.0   15.0   22.0   225.0
84       6099.0   19.310215   12.730402   4.0   12.0   15.0   23.0   225.0
85       8902.0   19.949562   13.065125   4.0   12.0   16.0   24.0   320.0
86      11745.0   22.133759   14.112948   4.0   13.0   18.0   26.0   170.0
87      15767.0   24.901884   18.518484   5.0   15.0   20.0   30.0   800.0
88      16014.0   28.687523   31.443071   6.0   17.0   24.0   35.0  3300.0
89      11324.0   32.169640   22.191063   7.0   19.0   26.0   40.0   500.0
90      14361.0   36.906622   23.941968   8.0   22.0   30.0   45.0   510.0
91      10564.0   43.224252   32.646402   7.0   26.0   38.0   51.0  2013.0
92       8871.0   51.037763   32.295930  11.0   32.0   45.0   60.0   750.0
93       5935.0   63.112216   43.665968  12.0   39.0   52.0   75.0   770.0
94       3449.0   81.436938   69.745545  13.0   48.0   63.0   90.0  1125.0
95       1406.0  109.235420  102.278905  20.0   55.0   75.0  120.0   973.0
96        482.0  159.292531  226.955589  20.0   65.0   97.0  160.0  2500.0
97        207.0  207.173913  229.087465  35.0   82.0  120.0  233.5  2000.0
98         69.0  245.492754  278.559246  50.0   86.0  140.0  275.0  1900.0
99         28.0  284.214286  210.734581  44.0  125.0  243.5  346.5   850.0
100        19.0  485.947368  410.142451  80.0  230.0  359.0  583.5  1500.0